[build]
  publish = "build"
  command = "yarn build"

# Production context: All deploys to the main
# repository branch will inherit these settings.
[context.production]
  command = "make production"
  [context.production.environment]
    NODE_VERSION = "9.4.0"
    REACT_APP_ARBITRATOR_ADDRESS = "0xaea35f89f98996ae06aac344ab4b9ce1731059c4"
    REACT_APP_ARBITRATOR_EXTRADATA = "0"
    REACT_APP_ARBITRATOR_TIMEOUT = "172800"
    REACT_APP_STORE_PROVIDER = "https://kleros.in"
    YARN_FLAGS = "--no-ignore-optional"

# Develop Branch Deploy context: All deploys that are not in
# an active Deploy Preview will inherit these settings.
[context.develop]
  command = "make staging"
  [context.develop.environment]
    NODE_VERSION = "9.4.0"
    REACT_APP_ARBITRATOR_ADDRESS = "0xaea35f89f98996ae06aac344ab4b9ce1731059c4"
    REACT_APP_ARBITRATOR_EXTRADATA = "0"
    REACT_APP_ARBITRATOR_TIMEOUT = "172800"
    REACT_APP_STORE_PROVIDER = "https://kleros.in"
    YARN_FLAGS = "--no-ignore-optional"
