[build]
  publish = "build/"
  command = "yarn build"

# Production context: All deploys to the main
# repository branch will inherit these settings.
[context.production]
  [context.production.environment]
    NODE_VERSION = "9.4.0"
    REACT_APP_ARBITRATOR_ADDRESS = "0x3af76ef44932695a33ba2af52018cd24a74c904f"
    REACT_APP_ARBITRATOR_EXTRADATA = "0"
    REACT_APP_ARBITRATOR_TIMEOUT = "172800"
    REACT_APP_STORE_PROVIDER = "https://kleros.in"
    YARN_FLAGS = "--no-ignore-optional"

# Develop Branch Deploy context: All deploys that are not in
# an active Deploy Preview will inherit these settings.
[context.develop]
  [context.develop.environment]
    NODE_VERSION = "9.4.0"
    REACT_APP_ARBITRATOR_ADDRESS = "0xA2D6CC4eCec4B1189F61dF4dD0a4FE06dfad0dEc"
    REACT_APP_ARBITRATOR_EXTRADATA = "0"
    REACT_APP_ARBITRATOR_TIMEOUT = "172800"
    REACT_APP_STORE_PROVIDER = "https://kleros.in"
    YARN_FLAGS = "--no-ignore-optional"
